// client/src/app/room/quiz/quiz.component.ts
import { Component, OnInit } from '@angular/core'
import { Router, ActivatedRoute, Params } from '@angular/router'
import { fadeInTransition } from '../../router.transition'
import { Room } from '../../models/room.model'
import { RoomService } from '../../services/room.service'
import { MatDialog, MatTableDataSource } from '@angular/material'
import { Question } from '../../models/question.model';
import { Answer } from '../../models/answer.model';
import { Globals } from '../../globals';
import { SocketEvents } from '../../helpers/utils';

@Component({
  selector: 'app-quiz',
  templateUrl: './quiz.component.html',
  styleUrls: ['./quiz.component.css'],
  animations: [fadeInTransition],
  host: { '[@fadeInTransition]': '' }
})

export class QuizComponent implements OnInit {

  TIME_OVER = 'TIME_OVER'
  ANSWER = 'ANSWER'
  LOADING = 'LOADING'
  CORRECT = 'CORRECT'
  WRONG = 'WRONG'
  SENT = 'SENT'
  UNAVAILABLE = 'UNAVAILABLE'
  ENDED = 'ENDED'

  room = <Room>{}
  question = <Question>{}
  mode = 'LOADING'
  progress = 0
  answered = false
  socket: any
  step = 0

  constructor(private roomService: RoomService,
    private router: Router,
    private dialog: MatDialog,
    private activatedRoute: ActivatedRoute) {
    this.socket = Globals.getSocket()
    activatedRoute.params.subscribe((res: Params) => {
      roomService.getQuiz(res.id).subscribe((res: Room) => {
        this.room = res
        if (this.room && !this.room.endedAt) {
          this.socket.emit(SocketEvents.Server.IN_ROOM, res.id)
          this.step = 10 / this.room.time
        } else if (this.room.endedAt)
          this.mode = this.ENDED
        else
          this.mode = this.UNAVAILABLE
      })
    })

    this.socket.on(SocketEvents.Client.QUESTION_RECEIVED, (q) => {
      console.log('QUESTION_RECEIVED')
      console.log(q)
      if (q.roomId == this.room.id) {
        this.question = q
        this.mode = q.answered ? this.SENT : this.ANSWER
        this.runTimer()
        this.progress = 0
      }
    })

    this.socket.on(SocketEvents.Client.FEEDBACK_ANSWER, (q) => {
      console.log('FEEDBACK')
      console.log(q)
      if (q.roomId == this.room.id) {
        this.question = q
        this.mode = q.feedback
      }
    })

    this.socket.on(SocketEvents.Client.FINISH_ROOM, res => {
      if (res.roomId == this.room.id) {
        this.room.score = res.score || 0
        this.mode = this.ENDED
      }
    })
  }

  ngOnInit() {
  }

  runTimer() {
    // this.progress += this.step
    // if (this.progress < 100 && !this.answered)
    //   setTimeout(() => {
    //     this.runTimer()
    //   }, 100)
    // else if (!this.answered) {
    //   this.progress = 0
    //   this.mode = this.TIME_OVER
    // }
  }

  answer(a: Answer) {
    this.answered = true
    this.mode = this.SENT
    this.socket.emit(SocketEvents.Server.SEND_ANSWER, {
      roomId: this.room.id,
      questionId: this.question.id,
      answerId: a.id
    })
  }
}
<div class="quiz-card">

  <div *ngIf="mode == UNAVAILABLE" class="unavailable">
    <span>Sala indisponível no momento</span>
  </div>

  <div *ngIf="mode != UNAVAILABLE">
    <div class="quiz-title">{{room.name}}</div>
    <div *ngIf="mode == ANSWER">
      <mat-progress-bar mode="indeterminate"></mat-progress-bar>
      <div class="quiz-points">Valendo {{question.points}} pontos</div>
      <div class="quiz-ask">{{question.description}}</div>
      <div class="quiz-answer-content">
        <div *ngFor="let a of question.answers">
          <div class="quiz-answer" (click)="answer(a)">
            {{a.description}}
          </div>
        </div>
      </div>
    </div>
  </div>

  <div *ngIf="mode == ENDED" class="unavailable">
    <span>esta sala foi finalizada</span>
    <br />
    <div class="score">
      Você fez
      <span>{{room.score}}</span> pontos.
    </div>
  </div>

  <div *ngIf="mode == TIME_OVER" class="quiz-feedback time-over">
    <div style="margin: 0 auto">
      <mat-icon>sentiment_very_dissatisfied</mat-icon>
    </div>
    <span>tempo acabou!</span>
  </div>

  <div *ngIf="mode == SENT" class="quiz-feedback sent">
    <div style="margin: 0 auto">
      <mat-icon>send</mat-icon>
    </div>
    <span>resposta enviada!</span>
  </div>

  <div *ngIf="mode == CORRECT" class="quiz-feedback correct">
    <div style="margin: 0 auto">
      <mat-icon>check</mat-icon>
    </div>
    <span>correto!</span>
  </div>

  <div *ngIf="mode === WRONG" class="quiz-feedback wrong">
    <div style="margin: 0 auto">
      <mat-icon>close</mat-icon>
    </div>
    <span>errado!</span>
  </div>

  <div *ngIf="mode == LOADING" class="loading">
    <mat-progress-spinner mode="indeterminate"></mat-progress-spinner>
  </div>
</div>

// client/react/src/scenes/quiz/Quiz.jsx
import React, { useState, useEffect } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import { LinearProgress } from '@material-ui/core'
import PropTypes from 'prop-types'
import { ClientSocket } from 'store/client-socket'

import { Wrong, Sent, Correct, TimeOver, Loading, Ended } from './Feedbacks'
import {
  Container, Title, TextPoints,
  TextQuestion, ContainerAnswers, AnswerButton
} from './styles'
import { QuizStatus, SocketEvents } from 'helpers'
import { roomService } from 'services'
import { startQuiz, answerSent, SocketActions } from 'store/actions'

export default function Quiz(props) {

  const [room, setRoom] = useState({})
  const id = Number(props.match.params.id.replace(':', ''))

  const quiz = useSelector(state => state.quizState)
  const language = useSelector(state => state.appState.language)
  console.log(language)
  const dispatch = useDispatch()

  useEffect(() => {
    loadRoom()
  }, [])

  async function loadRoom() {
    const room = await roomService.getQuiz(id)
    setRoom(room)
    if (room.endedAt) {
      dispatch(SocketActions.roomFinished())
    } else {
      dispatch(startQuiz(id))
      ClientSocket.send(SocketEvents.Server.IN_ROOM, id)
    }
  }

  // onInit(){
  // this.room = res
  //       if (this.room && !this.room.endedAt) {
  //         this.step = 10 / this.room.time
  //         this.socket = Globals.getSocket()
  //         if (this.socket)
  //           this.initSocket()
  //       } else if (this.room.endedAt)
  //         this.mode = this.ENDED
  //       else
  //         this.mode = this.UNAVAILABLE
  //     }

  function sendAnswer(answer) {
    dispatch(answerSent(answer))
    ClientSocket.send(SocketEvents.Server.SEND_ANSWER, {
      roomId: quiz.roomId,
      questionId: quiz.question.id,
      answerId: answer.id
    })
  }

  return (
    <Container>
      <Title>{room.name}</Title>
      {
        quiz.status === QuizStatus.ANSWER &&
        <div>
          <LinearProgress variant="indeterminate" style={{ marginBottom: 10 }} />
          <TextPoints>Valendo {quiz.question.points} pontos</TextPoints>
          <TextQuestion>{quiz.question.description}</TextQuestion>
          <ContainerAnswers>
            {quiz.question.answers.map(a => <AnswerButton
              onClick={() => sendAnswer(a)}
              key={a.id}>{a.description}</AnswerButton>)}
          </ContainerAnswers>
        </div>
      }
      {quiz.status === QuizStatus.TIME_OVER && <TimeOver />}
      {quiz.status === QuizStatus.SENT && <Sent />}
      {quiz.status === QuizStatus.CORRECT && <Correct />}
      {quiz.status === QuizStatus.WRONG && <Wrong />}
      {quiz.status === QuizStatus.LOADING && <Loading />}
      {quiz.status === QuizStatus.ENDED && <Ended score={quiz.score} lang={language} />}
    </Container >
  )
}

Quiz.propTypes = {
  match: PropTypes.object
}
